# Generated by Django 5.1.4 on 2025-01-26 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussion_forum', '0002_initial'),
        ('post_interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='angry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussion_forum.post'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='discussion_forum.post'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='haha',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hahas', to='discussion_forum.post'),
        ),
        migrations.AddField(
            model_name='haha',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hahas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nauseated',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nauseateds', to='discussion_forum.post'),
        ),
        migrations.AddField(
            model_name='nauseated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nauseateds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poop',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poops', to='discussion_forum.post'),
        ),
        migrations.AddField(
            model_name='poop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='angry',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='haha',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='nauseated',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='poop',
            unique_together={('user', 'post')},
        ),
    ]
