# Generated by Django 5.1.4 on 2025-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_interactions', '0006_angry_nauseated_poop'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
