# Generated by Django 5.1.4 on 2025-01-11 21:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_interactions', '0007_comment_media_data_comment_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
