# Generated by Django 5.1.2 on 2025-01-02 15:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0004_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
