# Generated by Django 5.1.4 on 2025-01-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0009_alter_post_author_alter_topic_author_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
