# Generated by Django 5.1.4 on 2025-01-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0010_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
