# Generated by Django 5.1.4 on 2025-01-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0011_remove_post_image_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
