# Generated by Django 5.1.2 on 2025-01-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_remove_user_user_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
