# Generated by Django 5.1.2 on 2025-01-02 15:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_remove_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
