# Generated by Django 5.1.2 on 2025-01-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_count',
        ),
    ]
