# Generated by Django 5.1.2 on 2025-01-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0003_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
