# Generated by Django 5.1.4 on 2025-01-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('haha', 'Haha'), ('comment', 'Comment'), ('dislike', 'Dislike'), ('message', 'Message')], default='unknown', max_length=50),
        ),
    ]
