# Generated by Django 5.1.4 on 2025-01-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('haha', 'Haha'), ('angry', 'Angry'), ('poop', 'Poop'), ('nauseated', 'Nauseated'), ('comment', 'Comment'), ('dislike', 'Dislike'), ('message', 'Message')], default='unknown', max_length=50),
        ),
    ]
